services:
    louvre_reservation.validator.antithousandbooking:
        class: Louvre\ReservationBundle\Validator\AntiThousandBookingValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: anti_thousand_booking }
