<?php

namespace Proxies\__CG__\Louvre\ReservationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \Louvre\ReservationBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'date', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'orderNumber', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'dayVisit', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'email', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'halfDay', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'total', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'stripeToken', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'tickets'];
        }

        return ['__isInitialized__', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'id', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'date', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'orderNumber', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'dayVisit', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'email', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'halfDay', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'total', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'stripeToken', '' . "\0" . 'Louvre\\ReservationBundle\\Entity\\Order' . "\0" . 'tickets'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderNumber($orderNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderNumber', [$orderNumber]);

        return parent::setOrderNumber($orderNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderNumber', []);

        return parent::getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDayVisit($dayVisit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDayVisit', [$dayVisit]);

        return parent::setDayVisit($dayVisit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDayVisit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDayVisit', []);

        return parent::getDayVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setStripeToken($stripeToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStripeToken', [$stripeToken]);

        return parent::setStripeToken($stripeToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getStripeToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStripeToken', []);

        return parent::getStripeToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setHalfDay($halfDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHalfDay', [$halfDay]);

        return parent::setHalfDay($halfDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getHalfDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHalfDay', []);

        return parent::getHalfDay();
    }

    /**
     * {@inheritDoc}
     */
    public function addTicket(\Louvre\ReservationBundle\Entity\Ticket $ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTicket', [$ticket]);

        return parent::addTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTicket(\Louvre\ReservationBundle\Entity\Ticket $ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTicket', [$ticket]);

        return parent::removeTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getTickets()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTickets', []);

        return parent::getTickets();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function isHalfDayValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHalfDayValid', []);

        return parent::isHalfDayValid();
    }

    /**
     * {@inheritDoc}
     */
    public function addTotal($tickets)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTotal', [$tickets]);

        return parent::addTotal($tickets);
    }

}
